"""Exception proto response."""
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exception.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exception.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x65xception.proto\",\n\tException\x12\x0e\n\x06\x64\x65tail\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x62\x06proto3')
)




_EXCEPTION = _descriptor.Descriptor(
  name='Exception',
  full_name='Exception',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail', full_name='Exception.detail', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='Exception.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['Exception'] = _EXCEPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Exception = _reflection.GeneratedProtocolMessageType('Exception', (_message.Message,), dict(
  DESCRIPTOR = _EXCEPTION,
  __module__ = 'exception_pb2'
  # @@protoc_insertion_point(class_scope:Exception)
  ))
_sym_db.RegisterMessage(Exception)


# @@protoc_insertion_point(module_scope)
